# These are supported funding model platforms

# GitHub Sponsors (up to 4 usernames)
github: [Pigletpeakkung]

# Patreon username
patreon: # Not currently active

# Open Collective username
open_collective: # Not currently active

# Ko-fi username
ko_fi: # Not currently active

# Tidelift platform-name/package-name (e.g., npm/babel)
tidelift: # Not applicable for portfolio projects

# Community Bridge project-name (e.g., cloud-foundry)
community_bridge: # Not applicable

# Liberapay username
liberapay: # Not currently active

# IssueHunt username
issuehunt: # Not currently active

# LFX Crowdfunding project-name (e.g., cloud-foundry)
lfx_crowdfunding: # Not applicable

# Polar username
polar: # Not currently active

# Buy Me a Coffee username
buy_me_a_coffee: thanattsitts

# Thanks.dev username
thanks_dev: # Not currently active

# Custom sponsorship URLs (up to 4)
custom: ['https://paypal.me/@thanattsittS', 'https://linktr.ee/ThanttEzekiel']
